### ISSUE TITLE
Normalize COVID-19 characteristics from Italy

### ISSUE THREAD

**Issue by Mdraugelis** [pennsignals/chime#10]
Update COVID-19 Characteristics Doc with Italian site data to feed CHIME
 https://docs.google.com/spreadsheets/d/1P1W6nLPYPoIqKmvKJWq1iUCkTsrPOu7DkOMTmWotJik/edit?usp=sharing

**Comment by Hanisha13** [comment]
update the google doc.  Not really a lot in that paper
