### ISSUE TITLE
The data table is un-readable for large numbers

### ISSUE THREAD

**Issue by Mdraugelis** [pennsignals/chime#21]

**Comment by Mdraugelis** [comment]
The table should resize to display all numbers OR be exportable.

![Screen Shot 2020-03-15 at 10 09 59 AM](https://user-images.githubusercontent.com/525828/76703090-25522980-66a5-11ea-9597-0fb2b8ed4259.png)

**Comment by therealthaibinh** [comment]
I wasn't able to recreate this issue, even with bigger numbers. I tried it in Chrome on a Mac and Edge on a Windows machine and the columns adjusted to larger numbers appropriately.
![image](https://user-images.githubusercontent.com/3888147/76710646-9adaeb80-66df-11ea-8572-7a43b48b3a40.png)

**Comment by sam-qordoba** [comment]
see https://github.com/CodeForPhilly/chime/issues/19
