### ISSUE TITLE
Allow user to specify R0 (in lieu of doubling time).

### ISSUE THREAD

**Issue by cjbayesian** [pennsignals/chime#23]
Calculation (extends "more info about this tool"):

We can compute the implicit $R_0$ from our doubling time inputs and our assumed duration of infectiousness $(1/\gamma)$. Since $R_0$ is the number of additional individuals infected by each infected individual when $I << S$, we can compute the growth rate $g$ as a function of $R_0$ and $\gamma$:
$$g = \gamma R_0 $$
From our previous equation for $g$, we can substitute and rearrange to find:
$$R_0 = (2^{1/T_d} - 1)/\gamma$$

So, for our $\gamma$ of 1/14 days, a doubling time of 4 days corresponds to an $R_0$ of 2.65.

**Comment by sam-qordoba** [comment]
https://github.com/CodeForPhilly/chime/issues/18
