### ISSUE TITLE
Toggle linear/log scaling of y-axes on plots.

### ISSUE THREAD

**Issue by cjbayesian** [pennsignals/chime#29]

**Comment by sam-qordoba** [comment]
@quinn-dougherty I think you said this is resolved?

**Comment by quinn-dougherty** [comment]
add a `bool` flag to functions that look like `def some_chart(*args) -> alt.Chart:`. if logscale is flagged, do something like `.encode(y=alt.Y("col", scale=alt.Scale("log") ... ` read the docs for specific syntax.

**Comment by sam-qordoba** [comment]
Ok, so, this is possible, we just need a way in the UI to toggle that flag?

**Comment by sam-qordoba** [comment]
moving to https://github.com/CodeForPhilly/chime/issues/22
