### ISSUE TITLE
Natural language summary of outputs

### ISSUE THREAD

**Issue by cjbayesian** [pennsignals/chime#30]
In addition to the output plots, it would help to have an automatically takeaway in words. For example:
- Peak admissions projected in XX days.
- ICU admissions projected to surpass XX in YY days.
- ...

**Comment by sam-qordoba** [comment]
Happy to help, I've worked on NLP/NLG stuff for the last 4 years

**Comment by sam-qordoba** [comment]
https://github.com/CodeForPhilly/chime/issues/17
