### ISSUE TITLE
Add CI tool for testing

### ISSUE THREAD

**Issue by mariekers** [pennsignals/chime#42]
- [Travis CI](https://travis-ci.org/) added and running on active PRs

**Comment by garysieling** [comment]
I could take this - is there a preference around a testing tool?

**Comment by mariekers** [comment]
@garysieling no preference - I've used travis so I put it in as an example but if you know of a better one specific to python (and ML models/tools) feel free to implement it

**Comment by garysieling** [comment]
Sounds good - I started running with travis

**Comment by garysieling** [comment]
Some updates from our slack conversation:
1. Goal - make sure the Penn version of this is easy to deploy
2. Goal - make sure this is easy for new places to adopt

Some potential next steps (pulled from slack discussion): 
1. Hook up Github actions
2. Document workflow for tagging releases
3. Document workflow to prove site has deployed
4. Script & document this workflow: fork the repo, spin up a commodity k8s cluster anywhere, drop a kubeconfig into GH Actions Secrets, and have an automated deploy-on-tag flow going

**Comment by sam-qordoba** [comment]
see https://github.com/CodeForPhilly/chime/issues/13
