### ISSUE TITLE
Update viz package

### ISSUE THREAD

**Issue by mariekers** [pennsignals/chime#43]
- Replace matplotlib with interactive viz package (altair, plotly, etc) to speed up app delivery and improve interactivity 
- replace visualizations with new package code

**Comment by therealthaibinh** [comment]
Another factor to consider is the amount of space each input (e.g. Currently Known Regional Infections, Currently Hospitalized COVID-19 Patients) takes up. It would be nice to be able to use the screen space more efficiently to minimize scrolling and fit other informative text/data. The current fix is to hide additional text/data behind checkbox toggles.

**Comment by quinn-dougherty** [comment]
i would do this https://github.com/pennsignals/chime/issues/29 at the same time

**Comment by quinn-dougherty** [comment]
https://github.com/pennsignals/chime/pull/58
