### ISSUE TITLE
The tool should not crash when the confirmed cases=0 and/or hospitalization=0

### ISSUE THREAD

**Issue by Mdraugelis** [pennsignals/chime#44]
There should be either instruction to use "1" instead of "0", or update the code to use 1 when someone enters 0.

currently the tool crashes.

**Comment by Mdraugelis** [comment]
![Screen Shot 2020-03-16 at 4 06 07 PM](https://user-images.githubusercontent.com/525828/76795634-113f2280-67a0-11ea-91d1-2c9ca75cbc9f.png)

**Comment by sam-qordoba** [comment]
moved to https://github.com/CodeForPhilly/chime/issues/10
