### ISSUE TITLE
Create method for Clinical owner to collect known cases in region

### ISSUE THREAD

**Issue by Mdraugelis** [pennsignals/chime#5]
1. A clinical owner of CHIME needs to quickly grab reliable figures to reset the model for a new day zero
2. A clinical owner of the Forecast tool to quickly grab the numbers to assess forecasting accuracy.

Known cases in Delaware + Chester + Montgomery+Bucks+Philly 

Data resides at:
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv

**Comment by cjbayesian** [comment]
This two issues. Please split.

**Comment by sam-qordoba** [comment]
see https://github.com/CodeForPhilly/chime/issues/20
