### ISSUE TITLE
App still unstable under high traffic

### ISSUE THREAD

**Issue by mdbecker** [pennsignals/chime#52]
We're still getting matplotlib errors and general app slowness under heavy user traffic

![image (9)](https://user-images.githubusercontent.com/1069047/76850666-3f634780-681e-11ea-8eae-f2930a2de3f6.png)

We applied a recommended fix from streamlit/streamlit#469 by switching the matplotlib backend which seemed to temporarily help until the user load increased further. 

Additionally our attempt to refactor the code base #6 seemed to make the app even slower and cause even more errors.

This issue is impossible to reproduce in development mode.

Some possible ideas for addressing this issue:
- Is it something to do with the way we're running the app on Heroku?
- Could switching to Altair based plot help? (#43)
- Do we need to abandon steamlit in favor of something else that might be more stable (voila or dash perhaps?)

**Comment by archydeberker** [comment]
We've deployed something similar: https://corona-calculator.herokuapp.com

We haven't had stability issues, although long latency and a memory leak are causing problems. We use Plotly for our graphs.

Let me know if you want to talk Streamlit or Heroku DevOps!

**Comment by tvst** [comment]
Hey @mdbecker , thanks for the bug report. I'll take a look at this later today, but from the error message my guess is this not directly related to load but rather some rare Streamlit+Matplotlib bug (possibly related to concurrency). If I'm right then switching to Altair would work around the bug. Also, Altair should be faster and generally lighter on the server.

Either way, I'll let you know when I have more information.

@archydeberker can you create separate bugs for your latency and memory leak problems? And please add whatever debug info you can, as those can be hard to diagnose from a distance :wink:

**Comment by quinn-dougherty** [comment]
altairization should be resolved by EoD today https://github.com/pennsignals/chime/pull/58

**Comment by mdbecker** [comment]
We moved to altair. Things look much better now. Thanks for the response. I will close!
